using System;
using System.Threading.Tasks;
using BudgetTracker.DataBase;
using BudgetTracker.Model;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using Microsoft.EntityFrameworkCore;

namespace BudgetTracker.ViewModel
{
    public partial class NewUserPageViewModel : ObservableObject
    {
        public event Action? RequestGoBack;
        public Action<int>? UserCreated;

        [RelayCommand]
        public void GoBack() => RequestGoBack?.Invoke();

        //Use fields with [ObservableProperty]; generator creates public PascalCase properties.
        [ObservableProperty]
        private string username = string.Empty;

        [ObservableProperty]
        private decimal monthlyBudget;

        [ObservableProperty] 
        private bool isBusy;


        // public IAsyncRelayCommand? CreateAccountCommand { get; }

        [RelayCommand(CanExecute = nameof(CanCreateAccount))]
        private async Task CreateAccountAsync()
        {
            var name = Username?.Trim();
            if (string.IsNullOrWhiteSpace(name))
                return;

      
           

       

     
            isBusy = true;
            try
            {
                await using var db = new BudgetDBContext();

                var user = await db.User
                    .Include(u => u.UserData)
                    .SingleOrDefaultAsync(u => u.Username == name);

                var success = false;

                if (user is null)
                {
                    user = new User
                    {
                        Username = name,
                        UserData = new UserData
                        {
                            UserBudget = MonthlyBudget,
                            UserBalance = MonthlyBudget
                        }
                    };

                    db.User.Add(user);
                    try
                    {
                        await db.SaveChangesAsync();
                        success = true;
                    }
                    catch (DbUpdateException)
                    {
                        // unique-index race: fetch winner as success
                        user = await db.User.Include(u => u.UserData)
                                            .SingleAsync(u => u.Username == name);
                        success = true;
                    }
                }
                else if (user.UserData is null)
                {
                    user.UserData = new UserData
                    {
                        UserBudget = MonthlyBudget,
                        UserBalance = MonthlyBudget
                    };
                    await db.SaveChangesAsync();
                    success = true;
                }
                else
                {
                    // If you *only* want to go back when a brand-new account was created,
                    // leave success = false here. If any success should go back, set true.
                    success = true; // <- optional: treat existing user as success
                }

                if (success)
                {
                    // 1) notify subscribers with the new/existing user id
                    UserCreated?.Invoke(user.Id);

                    // 2) then navigate back once
                    RequestGoBack?.Invoke();
                }
            }
            finally
            {
                isBusy = false;
                CreateAccountCommand?.NotifyCanExecuteChanged();
            }


        }

        private bool CanCreateAccount()
            => !string.IsNullOrWhiteSpace(Username) && MonthlyBudget >= 0;

        // Match nullable type generated by [ObservableProperty]
        partial void OnUsernameChanged(string? value)
            => CreateAccountCommand?.NotifyCanExecuteChanged();

        partial void OnMonthlyBudgetChanged(decimal value)
            => CreateAccountCommand?.NotifyCanExecuteChanged();
    }
}
